[[plugin.prepend_fetchers]]
id   = "git"
url  = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*/"
run  = "git"

[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true
linemode       = "size"


[opener]
edit = [
    { run = '${EDITOR:=nvim} "$@"', block = true, desc = "$EDITOR" },
]
play = [
    { run = 'mpv "$@"', orphan = true, desc = "mpv" },
]
extract = [
    { run = 'ya pub extract --list "$@"', desc = "Extract here" },
]



[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { mime = "application/json", use = "edit" },
    { mime = "application/x-zip-compressed", use = "extract" },
    { mime = "application/x-tar", use = "extract" },
    { mime = "application/x-bzip", use = "extract" },
    { mime = "application/x-bzip2", use = "extract" },
    { mime = "application/x-7z-compressed", use = "extract" },
    { mime = "application/x-rar", use = "extract" },
    { mime = "application/xz", use = "extract" },
    { mime = "*", use = "open" },
]

